### ISSUE TITLE
Fix console log warnings

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#247]
![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/3db9205c-5694-4ac1-824b-9dbe62f69949)

**Comment by Unesdala** [comment]
@JoshuaVSherman - I've been poking around looking for some more definitive answers on this for a bit now, and I'm not sure if it's something we can fix on our end.

As far as I'm aware, because the cookies that are getting flagged are from google and facebook, I don't think we can set those cookies ourselves. From what I understand about it all, that will have to wait for them to fix on their end, given it's a 3rd party cookie.

Facebook doesn't look like it's setting anything. Google is setting two of its own from accounts.google.com (I'm guessing in relation to the login API), and another 2 under our domain.

Final one, which is set to samesite=none; secure; is from .dropboxusercontent.com.

This might be something we have to just wait for google and facebook to fix. If it is on their end, they'll have to fix it before Chrome 80 as is, or else their own API's are going to break.

**Comment by Unesdala** [comment]
https://web.dev/samesite-cookies-explained/

> If you rely on any services that provide third-party content on your site, you should also check with the provider that they are updating their services. You may need to update your dependencies or snippets to ensure that your site picks up the new behavior.

**Comment by JoshuaVSherman** [comment]
@Unesdala ok i'll look into this later then, thanks again for the research
