### ISSUE TITLE
New setup failing

### ISSUE THREAD

**Issue by GigabyteCrippler** [WebJamApps/JaMmusic#303]
After new clone and npm install, its throwing many errors, any help on these

1) Uncaught TypeError: scc.on is not a function 
2) Uncaught (in promise) TypeError: scc.on is not a function
3) react-dom.development.js?61bb:530 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

**Comment by JoshuaVSherman** [comment]
Good evening,  you need to run the web jam sockets project in order to
start the JaMmusic project

**Comment by JoshuaVSherman** [comment]
@GigabyteCrippler the first error is because socketCluster-client cannot connect to the socketCluster-server, you need to pull down and run this project locally before you can start up the JaMmusic front-end project because it needs to connect to the other project.
https://github.com/WebJamApps/WebJamSocket

after you clone and install this project, you will also need to copy over the .env.example file to make a new .env file, this is used for global variables for the project with nodejs Process.Env, and you will need to provide connection to an instance of MongoDB for both development and tests, free mongo in the cloud is availabe either by using mlab or mongodb atlas, if you don't have or are unable to setup your own free mongodb for this project, contact me and I will provide the uri to my test db that you can use for both connections, but when you run the tests, your development data will be erased. Ping me on hangouts if you need further instructions at joshua.v.sherman@gmail.com

In addition, if you are going to be logging into the JaMmusic to access the admin dashboard, then you will need to install the https://github.com/WebJamApps/web-jam-back project, which handles authentication and has an email client. It also connects to an instance of mongodb, and the environment variables there will need to be updated to reflect your google admin account (for auth with google), your sendgrid account (for sending emails), and your mongodb instance again for both development and test use cases.

**Comment by JoshuaVSherman** [comment]
@GigabyteCrippler did the above information help you to get the projects running? If so, I will close this issue now.
