### ISSUE TITLE
Apply security fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#96]
Remediation
Upgrade websocket-extensions to version 0.1.4 or later. For example:

websocket-extensions@^0.1.4:
  version "0.1.4"
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by Unesdala** [comment]
@JoshuaVSherman - Are you wanting an image of the player, or were you wanting an embedded player like spotify has?

I can do an image that has the player in it, but they're not accepting new partners for being able to embed music so it's playable in the share itself at the moment.

https://developers.facebook.com/docs/opengraph/music/
https://developers.facebook.com/docs/opengraph/guides/music.playlists/

The only (possible) workaround I'm aware of is serving up the songs in video format, instead of mp3, and hoping they'd show the preview like yt and the like does (And then just changing the meta data accordingly) but there's not a 100% guarantee that would work.

**Comment by JoshuaVSherman** [comment]
Ok thanks for doing the research,  let's put this issue off for now then.
